# This is a basic workflow to help you get started with Actions

name: generate animation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: platane
          svg_out_path: dist/github-contribution-grid-snake.svg

